### ISSUE TITLE
Feature Request: `GetStrict` method

### ISSUE THREAD

**Issue by ghostsquad** [stretchr/objx#111]
I desire a method that attempts to get a subkey without parsing the key value I'm providing. I'm not sure how to do that currently.

**Comment by geseq** [comment]
Do you mean something like:
`m.Get(key).Inter()`

If not can you provide an example of what you mean? I’m not entirely sure I understand.

**Comment by ghostsquad** [comment]
I don't want the parameter of Get to be interrupted as a selector. It may
contain periods and other characters in that realm

Cheers,
Wes

**Comment by geseq** [comment]
There isn’t a way to do that at the moment. However, you can change the `PathSeparator` and use a separator that works for you.

If you still need the strict getter, please feel free to create a PR.
