### ISSUE TITLE
dealing with slices

### ISSUE THREAD

**Issue by Digl** [stretchr/objx#116]
when I have the following json: 
[{"key": "value"}.{"key2": "value2"}]

objx.FromJSON fails with the error:
cannot unmarshal array into Go value of type objx.Map

how should this be handled?
I am using v.0.3.0

**Comment by geseq** [comment]
use `objx.FromJSONSlice()`

**Comment by geseq** [comment]
I've also tagged the latest version so godoc is updated to reflect this and some of the other recent updates
