### ISSUE TITLE
Please cut a release

### ISSUE THREAD

**Issue by philtay** [stretchr/objx#21]
SemVer users will be grateful for it! Thanks.

**Comment by matryer** [comment]
@philtay would you like to join this project as a maintainer?

**Comment by philtay** [comment]
@matryer thanks for the offer. Unfortunately I don't have enough time to join as an "active" maintainer. Anyway I'd be grateful if you could tag the latest commit as v1.0.0. It won't take more than 2 minutes and you can do it directly from the GitHub website.

**Comment by adamdecaf** [comment]
@matryer I'd be interested in being a maintainer. This library is used by quite some other projects.

**Comment by Hanzei** [comment]
@matryer I would also like to become a maintainer of this project.

**Comment by matryer** [comment]
Welcome aboard guys. I no longer use this project, but if you do, please consider maintaining it.

**Comment by Hanzei** [comment]
Version 0.1 is cut: https://github.com/stretchr/objx/releases/tag/v0.1

**Comment by Hanzei** [comment]
V0.1.1 just got releases https://github.com/stretchr/objx/releases/tag/v0.1.1
