### ISSUE TITLE
Get an Int value from JSON doesn't work

### ISSUE THREAD

**Issue by webliupeng** [stretchr/objx#22]
```
o, err := objx.FromJSON(`{"foo": 1}`)
 if (err != nil) {
  panic(err)
}
println("foo", o.Get("foo").Int64())
```
It's return 0.

**Comment by DineshGuptaa** [comment]
It is give us value but in form Float64 instead of Int64 `println("foo", o.Get("foo").Float64())`. It will return value  `foo +1.000000e+000` 
I am unable to find why lib behave like this?

**Comment by Hanzei** [comment]
#59 fixed this problem.
```
o, err := objx.FromJSON(`{"foo": 1}`)
 if (err != nil) {
  panic(err)
}
println("foo", o.Get("foo").Int())
```
will return 1
