### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by Hanzei** [stretchr/objx#24]
CI via travis should be added

**Comment by Hanzei** [comment]
@matryer I would like to take care of this, but only the administrator can do this. Would you grand me the required permission or add it yourself (See https://travis-ci.org/stretchr/objx)?

**Comment by matryer** [comment]
Done.

**Comment by Hanzei** [comment]
Travis is moving to http://travis-ci.com/. I have send an Acess request. Mind adding this repro to travis-ci.com?
