### ISSUE TITLE
Add static program analysis

### ISSUE THREAD

**Issue by Hanzei** [stretchr/objx#34]
We should measure code coverage to improve your code base.

**Comment by Hanzei** [comment]
@matryer Same problem as with the CI. Can you add this rep to https://codeclimate.com/?

**Comment by Hanzei** [comment]
Ping @matryer

**Comment by matryer** [comment]
@Hanzei Would you like to become a maintainer of this repo?

**Comment by Hanzei** [comment]
@matryer Yes

**Comment by matryer** [comment]
Done.

**Comment by Hanzei** [comment]
Thanks!
