### ISSUE TITLE
Tag v0.1 as v0.1.0

### ISSUE THREAD

**Issue by leighmcculloch** [stretchr/objx#80]
vgo requires that versions have three parts, like v0.1.0, but the only version tagged for objx is `v0.1`, and so vgo is unable to use that version. Could you please add a tag at the same commit as `v0.1`, and name it `v0.1.0`?

You can do this by:

```
git tag -a v0.1.0 v0.1
git push origin v0.1.0
```

This is required to close stretchr/testify#607.

**Comment by Hanzei** [comment]
V0.1.1 just got released https://github.com/stretchr/objx/releases/tag/v0.1.1

**Comment by leighmcculloch** [comment]
Thanks @Hanzei !

**Comment by leighmcculloch** [comment]
@Hanzei I see you created the new tag, but it's not at the same sha. The version needs tagging at the same sha, not a new sha. Otherwise vgo won't be able to pull in version v0.1.0.

**Comment by Hanzei** [comment]
I just taged a new version. can't you use v0.1.1?

**Comment by leighmcculloch** [comment]
The new version is a different sha. Can you add a tag for the existing sha that v0.1 points to? Then testify can update it's dependency reference without changing which sha it references.

**Comment by leighmcculloch** [comment]
If you're up for doing this but not sure how I can help.

**Comment by Hanzei** [comment]
It should be fixed now

**Comment by leighmcculloch** [comment]
Thanks!
