### ISSUE TITLE
Unable to select map key with dot

### ISSUE THREAD

**Issue by cretz** [stretchr/objx#89]
If I have a map where the keys may be domain names and the values are some object, how do I select a field on the value for key "google.com" via `Get`?

**Comment by hanzei** [comment]
A test case would be great!

**Comment by cretz** [comment]
https://github.com/cretz/objx/commit/808954a2151189a03ff5ac68029bc89572ab4eff

**Comment by hanzei** [comment]
I see. What would be your suggestion to fix this? Escape with `\.`?

**Comment by earncef** [comment]
One option would be to make the `.` and `[]` interchangeable for maps. So rather than escape separately, `[]` could be used as the accessor.

That is:
```
Get("a.b") == Get("a[b]")
```

**Comment by hanzei** [comment]
I like this idea. Are you interested in implementing it?

**Comment by earncef** [comment]
Yeah, I'll work on it.
